# @package _global_

defaults:
  - override /model/combiner: mlp_gauss
  - override /model/paper_embedder: specter

trainer:
  max_time: "00:12:00:00"

data:
  batch_size: 32

model:
  lr: 0.001

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model.paper_embedder.frozen: true, false
